# ICP project - Block Editor

FLAGS=-o
TARGET=blockeditor # name of program
FILES=main.cc blocks.cc port.cc types.cc # all source files

# $^ contains names of all dependencies
all: $(FILES)
	g++ $(FLAGS) $(TARGET) $^